# -*- coding: utf-8 -*-
"""Abbas Ahammed Python Data Analytics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hinFjnmaaieY_m1IPrZ3Juab1ZHHdYIB
"""



import pandas as pd 
import numpy as np
df=pd.DataFrame(pd.read_csv("/content/train (1).csv")
df.head()
df.shape
df.isnull().sum()
drop_col=df.isnull().sum()[df.isnull().sum()>(35/100 * df.shape[0])]
print(drop_col)
print(df)
drop_col.index
print(drop_col)
df.drop(drop_col.index, axis=1,inplace=True)
print(df.drop)
print(df.isnull().sum())
df.fillna(df.mean(),inplace=True)
df.isnull().sum()
df['Embarked'].describe ()
df['Embarked'].fillna('S',inplace=True)
df.isnull().sum()
df.corr()
df[' Familysize'] = df['Sibsp']+df[ 'Parch ']
df.drop(['Sibsp', 'Parch'], axis=1, inplace=True)
df.corr()
df['Alone'] = [0 if df['FamilySize '][i]>0 else 1 for i in df.index]
df.head()
df.groupby(['Alone'])["Survived"].mean()
df[['Alone','Fare']].corr()
df['Sex'] = [0 if df['Sex '][i]=='male' else 1 for i in df.index] 
df.groupby(['Sex']) ['Survived'].mean()
df[['Alone','Fare']].corr()